package com.ute.ticket.organization.application.service;

import com.ute.ticket.organization.application.command.CreateOrganizationCommand;
import com.ute.ticket.organization.application.port.in.CreateOrganizationUseCase;
import com.ute.ticket.organization.application.port.out.OrganizationMemberRepository;
import com.ute.ticket.organization.application.port.out.OrganizationRepository;
import com.ute.ticket.organization.application.result.OrganizationResult;
import com.ute.ticket.organization.domain.entity.Organization;
import com.ute.ticket.organization.domain.entity.OrganizationMember;
import com.ute.ticket.organization.domain.enums.MemberRole;
import com.ute.ticket.shared.exception.BadRequestException;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
@Transactional
public class CreateOrganizationService implements CreateOrganizationUseCase {

    private final OrganizationRepository organizationRepository;
    private final OrganizationMemberRepository organizationMemberRepository;

    @Override
    public OrganizationResult execute(CreateOrganizationCommand cmd) {
        Long ownerId = cmd.getOwnerId();

        String slug = cmd.getSlug();
        boolean autoGenerated = slug == null || slug.isBlank();
        if (autoGenerated) {
            slug = generateSlug(cmd.getName());
            slug = findUniqueSlug(slug);
        }

        Organization organization = Organization.create(
                cmd.getName(),
                slug,
                cmd.getDescription(),
                cmd.getLogoUrl(),
                cmd.getWebsite(),
                ownerId
        );

        if (!autoGenerated && organizationRepository.existsBySlug(organization.getSlug())) {
            throw new BadRequestException("Organization slug already exists");
        }

        organization = organizationRepository.save(organization);

        OrganizationMember owner = OrganizationMember.create(
                organization.getId(),
                ownerId,
                MemberRole.OWNER
        );
        owner.activate();
        organizationMemberRepository.save(owner);

        return OrganizationResult.from(organization);
    }

    private String generateSlug(String name) {
        return name.trim().toLowerCase()
                .replaceAll("[^a-z0-9\\s-]", "")
                .replaceAll("\\s+", "-")
                .replaceAll("-+", "-");
    }

    private String findUniqueSlug(String baseSlug) {
        String candidate = baseSlug;
        int counter = 1;
        while (organizationRepository.existsBySlug(candidate)) {
            candidate = baseSlug + "-" + counter;
            counter++;
        }
        return candidate;
    }
}
