package com.ute.ticket.event.application.service;

import com.ute.ticket.event.application.command.RenameCategoryCommand;
import com.ute.ticket.event.application.port.in.RenameCategoryUseCase;
import com.ute.ticket.event.application.port.out.CategoryRepository;
import com.ute.ticket.event.application.result.CategoryResult;
import com.ute.ticket.event.domain.entity.Category;
import com.ute.ticket.shared.exception.BadRequestException;
import com.ute.ticket.shared.exception.NotFoundException;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
@Transactional
public class RenameCategoryService implements RenameCategoryUseCase {

    private final CategoryRepository categoryRepository;

    @Override
    public CategoryResult execute(RenameCategoryCommand cmd) {
        Category category = categoryRepository.findById(cmd.getId())
                .orElseThrow(() -> new NotFoundException("Category not found"));

        String slug = cmd.getSlug();
        boolean autoGenerated = slug == null || slug.isBlank();
        if (autoGenerated) {
            slug = generateSlug(cmd.getName());
            slug = findUniqueSlug(slug);
        }

        if (!category.getName().trim().equalsIgnoreCase(cmd.getName())
                && categoryRepository.existsByNameIgnoreCase(cmd.getName())) {
            throw new BadRequestException("Category name already exists");
        }

        if (!autoGenerated && !category.getSlug().equals(slug)
                && categoryRepository.existsBySlug(slug)) {
            throw new BadRequestException("Category slug already exists");
        }

        category.rename(cmd.getName(), slug);
        category = categoryRepository.save(category);

        return CategoryResult.from(category);
    }

    private String generateSlug(String name) {
        return name.trim().toLowerCase()
                .replaceAll("[^a-z0-9\\s-]", "")
                .replaceAll("\\s+", "-")
                .replaceAll("-+", "-");
    }

    private String findUniqueSlug(String baseSlug) {
        String candidate = baseSlug;
        int counter = 1;
        while (categoryRepository.existsBySlug(candidate)) {
            candidate = baseSlug + "-" + counter;
            counter++;
        }
        return candidate;
    }
}
